'LAMBDA_MIN:'  '$lambda_min'
'LAMBDA_MAX:'  '$lambda_max'
'LAMBDA_STEP:' '$delta_lambda'
'MODELINPUT:'   '$input_model'
'MARCS-FILE:' '$marcsfile'
'MODELOPAC:' '$opacity_file'
'METALLICITY:' '$metallicity'
'ALPHA/Fe:' '$alpha_over_iron'
'HELIUM:' '$helium_fraction'
'R-PROCESS:' '$r_process_fraction'
'S-PROCESS:' '$s_process_fraction'
'INDIVIDUAL ABUNDANCES:' '0'
'XIFIX:' '$xifix'
$turbulence_velocity
