'LAMBDA_MIN:'  '$lambda_min'
'LAMBDA_MAX:'  '$lambda_max'
'LAMBDA_STEP:' '$delta_lambda'
'MODELINPUT:'
'MARCS-FILE:'
'MODELOPAC:'
'METALLICITY:'
'ALPHA/Fe:'
'HELIUM:'
'R-PROCESS:'
'S-PROCESS:'
'INDIVIDUAL ABUNDANCES:'
'XIFIT:'
$turbulence_velocity
